### ISSUE TITLE
Doesn't work on v45

### ISSUE THREAD

**Issue by jakeb072001** [EBro912/QuickRestart#1]
I use /restart and get the confirmation message but typing confirm after does nothing.
Using /restart again after this doesn't even give me a confirmation and just shows /restart in chat.

Would be nice if this could be fixed when you have the time.

**Comment by LordKanelsnegle** [comment]
![image](https://github.com/EBro912/QuickRestart/assets/25708893/c7faab77-58a0-4e39-ae7c-619863e89b7d)
It seems the method name may have changed in v45 - possibly "EndPlayersFiredSequenceClientRpc" now? I'm not 100% sure.

**Comment by LordKanelsnegle** [comment]
Nevermind, cloned locally and recompiled it. Worked correctly with no issues. Seems like it just needed to be compiled with the latest version of the game's dlls.

**Comment by EBro912** [comment]
Thanks for the info, I'll release a version soon with the latest dlls.
